---
title: "hydromantes note"
format: html
editor: visual
---

*HYDROMANTES PLATYCEPHALUS* (Mount Lyell Salamander).
LENTIC HABITAT USE.

```{r}
#| include: false
#| code-fold: true

# Load required packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(here, readr, dplyr, tidyr, stringr, magrittr, geosphere)

# Read and clean Rovito (2010) Appendix CSV file of Hydromantes collection localities
rovito <- read_csv(here("data", "Rovito_2010_MolecularEcology_appendix.csv")) %>%    # Read CSV file
  rename_with(~ str_replace_all(tolower(str_trim(.x)), " ", "_")) %>%  # Remove leading/trailing spaces, lowercase, replace spaces with underscores
  separate_rows(`catalogue_number`, sep = ",\\s*") %>%   # Split by comma
  mutate(
    catalogue_number = str_trim(catalogue_number),     # Remove leading/trailing spaces
    catalogue_number = str_remove_all(catalogue_number, "[^0-9]"), # Keep only digits
    catalogue_number = as.integer(catalogue_number)  # format as integer
  ) %>%
  filter(catalogue_number != "")                         # Drop any empty entries

# Read and clean Arctos CSV file of Hydromantes collection localities
arctos <- read_csv(here("data", "ArctosData_hydromantes_23oct2025.csv")) %>% # Read CSV file
  rename_with(~ tolower(str_trim(.x))) %>%  # Remove leading/trailing spaces, lowercase
  mutate(
    guid = str_trim(guid),     # Remove leading/trailing spaces
    guid = str_remove_all(guid, "[^0-9]"), # Keep only digits
    guid = as.integer(guid),    # format as integer
    spec_locality = str_replace_all(spec_locality, "Smith's Lake, Desolation Wilderness area", "Smith Lake, Desolation Wilderness area, El Dorado National Forest"), 
    spec_locality = str_replace_all(spec_locality, "E side Smith Lake, Desolation Wilderness", "East side of Smith Lake, Desolation Wilderness, Eldorado National Forest")
  ) %>%    # Replace similar descriptions of the same site with identical descriptions
  filter(guid != "")
  
# Create new Arctos table from which Rovito (2010) records are removed
arctos_norovito <- arctos %>% 
  anti_join(rovito, join_by(guid == catalogue_number))

# Distinct non-Rovito Arctos localities that are associated with lentic habitats
arctos_norovito_lentic <- arctos_norovito %>% 
  filter(str_detect(spec_locality, regex("lake|pond", ignore_case = TRUE))) %>%
  distinct(spec_locality)

# Distinct Rovito localities that are associated with lentic habitats
rovito_lentic <- rovito %>% 
  filter(str_detect(locality, regex("lake|pond", ignore_case = TRUE))) %>%
  distinct(locality)

# Calculate distances between localities
locations <- tibble(
  site = c("coyote", "laurel"),
  x = c(-118.4764, -118.4920),   # Longitude (°)
  y = c(36.3601, 36.3661)        # Latitude (°)
)

ref_lon <- -118.5554   # Define a reference point (Bullfrog Lakes)
ref_lat <- 36.3948   

locations <- locations %>%   # Calculate distance (in meters) from reference point to each site
  mutate(distance_m = distHaversine(cbind(x, y), c(ref_lon, ref_lat)))

dist_coyote <- round(locations$distance_m[locations$site == "coyote"] / 1000, 1)   # Extract values for inline use
dist_laurel <- round(locations$distance_m[locations$site == "laurel"] / 1000, 1)  
```

*Hydromantes platycephalus* is endemic to California's Sierra Nevada mountains (USA), where it is found at elevations ranging from 1220 to 3658 m.
Across its range, it is closely associated with damp, rocky habitats, including talus piles, bedrock outcrops, flat rocks on bedrock or decomposed granite, under rocks at the edge of streams, and in waterfall spray zones (Wake and Papenfuss 2005. *In* Lannoo \[ed.\], Amphibian Declines: The Conservation Status of United States Species, pp. 783--784. University of California Press, Berkeley, California; Hansen and Shedd 2025. California Amphibians and Reptiles. Princeton University Press, Princeton, New Jersey).
Despite the abundance of lakes and ponds in the higher elevations of the Sierra Nevada, many with rocky shorelines that seem suitable for *H. platycephalus*, we are not aware of any published accounts describing *H. platycephalus* utilizing such lentic habitats.
Rovito (2010. Molecular Ecology 19: 4554--4571, Appendix) lists `r n_distinct(rovito$locality)` localities from which he collected *H. platycephalus*.
Of these, 13 are described as lakes (e.g., "Peeler Lake", "east side of Vogelsang Lake").
However, in all such cases, salamanders were actually collected from seep habitat on the rocky slopes above the lake (Rovito, personal communication).
In addition, a search of the Arctos online collection management system (https://arctos.database.museum/; 23 Oct 2025), a database that includes over 5 million records from natural and cultural history collections, produced `r nrow(arctos)` *H. platycephalus* records from `r n_distinct(arctos$spec_locality)` distinct localities.
After removing the Rovito (2010) localities, only six of `r n_distinct(arctos_norovito$spec_locality)` localities (`r round(6/((n_distinct(arctos_norovito$spec_locality)))*100)`%) are directly attributed to lentic habitats.
As previously, for most or all of these localities, it is likely that a lake name was used as a general locality description, but that the salamanders were actually collected from a nearby non-lentic habitat.
In summary, it is apparent that *H. platycephalus* is rarely, if ever, described as using lentic habitats.
Here, we provide the first unambiguous description of *H. platycephalus* from lake habitats, including in three distinct areas in Sequoia, Kings Canyon, and Yosemite National Parks.

In Sequoia National Park, on 06 Aug 2011 (2030-2130 h), RK searched for *H. platycephalus* in seeps flowing over granite outcrops above and approximately 300 m west of an unnamed lake (lake id = 20279; 36.3584°N, -118.4712°W, WGS 84, 3292 m) located in the headwaters of Coyote Creek.
On 07 Aug 2011 (approximately 2100 h), RK searched similar habitat above and approximately 300 m west of an unnamed lake (site id = 20276; 36.3671°N, -118.4884°W, WGS 84, 3341 m) located in the headwaters of Laurel Creek.
Coyote and Laurel Creeks are located west of the Sierra Nevada crest, and are tributaries of the Kern River.
Despite the searched sites being `r dist_coyote` km and `r dist_laurel` km, respectively, southeast of the southernmost known *H. platycephalus* locality west of the Sierra Nevada crest, 5--10 *H. platycephalus* were found at each location.
The Laurel Creek area was surveyed again in 2024 (by FP and RK) and 2025 (by CS and RK), with a focus on lake 20276.
20276 is a typical Sierra Nevada alpine lake, with a surface area of 1.7 ha, maximum depth of 12.5 m, and a shoreline composed almost entirely of granite bedrock and boulder, interspersed with short stretches of meadow vegetation and sandy beach.
During 14--16 July 2024, we conducted one diurnal survey (0910-1210 h) and two nocturnal surveys (2130--2315 h) of the entire shoreline and associated inlet and outlet streams of 20276, and one survey of the original bedrock outcrop locality (approximately 2200 h).
During the diurnal and nocturnal surveys, 1-2 surveyors walked the lake shore slowly, searching all habitats, including rock crevices, overhanging banks, and sandy beaches.
During the diurnal survey of 20276, no *H. platycephalus* were found.
During the two nocturnal surveys of 20276, we observed a total of 9 *H. platycephalus* (2 on 15 July, 7 on 16 July), all on the northeast shore.
We found no *H. platycephalus* at the original outcrop locality.
In 2025, we repeated this survey, conducting one diurnal survey (12 July, 0900--1110 h) and two nocturnal surveys of the entire shoreline of 20276 (12 July, 2130--2345 h; 13 July, 2140--2310 h), and one nocturnal survey of the original outcrop locality (13 July, approximately 2330 h)<!--# Cob, can you verify this date and time? I neglected to add it to my field notebook.  -->.
Again, we found no *H. platycephalus* during the diurnal survey of 20276 or the nocturnal survey of the original outcrop locality.
However, we saw 20-30 *H. platycephalus* during each of the two nocturnal surveys of 20276, and salamanders were concentrated on the southeast and northeast shorelines.
In both years, *H. platycephalus* seen at 20276 were observed on wet rocks and moss on the shore within 0--1 m of the lake.

On 08--09 August 2025, PL, GL, and JP<!--# Who is "JP"? (Jacob Politi on the SEKI aquatics crew was present for H. platycephalus observations at Goddard with PL and GL. We texted him to see if he remembered anything else but should discuss authorship.) --> surveyed an unnamed lake west of Mount Goddard in Kings Canyon National Park (site id = 10114; 37.1020°N, -118.7371°W, WGS 84, 3409 m).
This alpine lake is at the headwaters of the South Fork San Joaquin River, has a surface area of 6.6 ha, a maximum depth of 28.5 m, and a shoreline composed of metavolcanic rock and meadow vegetation.
During diurnal surveys conducted on 08 August and 09 August (08 August 1140--1710; 09 August, 1050--1320 h) of the entire lake shoreline and associated inlets and outlets, 7 *H. platycephalus* <!--# 5 were found on 08 August and 2 were found on 09 August in the same locality with possible overlap in individuals. How should we report the numbers? 5? -->were found along the northeastern inlet of 10114.
These salamanders were found under rocks in the spray zone of a small waterfall approximately 20 m <!--# Verify this distance with PL. One of the individuals that i flipped was at a second, higher waterfall. After doing some measuring on Caltopo, i'd estimate that one at 50m from the Lake -PL -->up the inlet.
During a nocturnal survey of the entire lake shoreline and northeastern inlet of 10114 on 08 August (2120--2330 h), we observed two *H. platycephalus* in the same locality in the northeastern inlet and three *H. platycephalus* on the lake shoreline.
Two of these three salamanders were under an overhanging grassy bank within 0--1 m of the lake and one was approximately 5 m from the lake shore on a dry, vegetated slope.

<!--# Text for likely deletion: three smaller unnamed lakes to the north (located near 37.11124°N, -118.73734°W, 3495 m) for three consecutive days on 08 August – 10 August 2025.  -->

In 2024, PL and GL <!--# AC did not suvey with us for H. platycephalus -GL-->surveyed an unnamed lake (lake ID = 70413) in Yosemite National Park (37.7198°N, -119.2803°W, WGS 84, 3322 m) for *H. platycephalus*.
The lake is located at the headwaters of the Lyell Fork of the Merced River, and has a surface area of 2.3 ha and a maximum depth of 10.5 m.
On 22 July, PL and GL conducted a nocturnal survey (2130-2245 h) of the granite talus habitat above 70413, the northern inlet, and the northwestern shoreline of the lake.
Along the northern inlet, 11 adult *H. platycephalus* were observed occupying granite bedrock, talus, moss substrate, and meadow habitat bordering the creek and within 150 m of the lake <!--# Verify this (100 or 150m I would say -GL, I did not record a distance in my notebook but looking on Caltopo it resonably could've been 150m, changing it to that -PL)-->.
No individuals were observed in the talus habitat above the lake or along the northwestern lake shore.
On 23 July, PL conducted a nocturnal survey of the entire shoreline of 70413 and associated inlet and outlet streams (2150-0200 h).
No *H. platycephalus* were observed along the northern inlet where they were seen the previous night.
However, a single salamander was observed on the northern shoreline, on a vegetated bank within 1 m <!--# Verify the accuracy of this or update with a more precise distance (I didn't write anything down about distance from the lake in my notebook, this was from memory. It was on the edge of the bank, but i can't recall if there was sandy beach zone between the bank and lake in that location -PL) -->of the lake.
In 2025, PL, GL, and LW again searched site 70413 for *H. platycephalus*.
On 18 August, during a diurnal survey of the lake shore and associated inlet and outlet streams (1250--1750), no salamanders were seen.
On 19 August, we conducted a nocturnal survey (2100-2230 h) of the northern inlet and the northern lake shore.
Two *H. platycephalus* were observed along the inlet, within 100 m of the lake.
On the northern lake shore, we found \> 60 salamanders.
Most were found 0--1 m from lake <!--# Looking at photos of the lake shoreline, i don't think any individuals were seen further than 0.5m, but others should confirm -PL-->, including on mossy substrate, in meadow vegetation, and at the base of a grassy bank along a sandy shore. Notably, three individuals were found submerged in shallow water at the shoreline, and all three were actively moving along the lake substrate <!--# Verify accuracy of this sentence  (I don't remember them locomoting anywhere but they were all definitely alive -GL, I remember them wriggling a bit (possibly influenced by our presence) but being largely stationary -PL)-->.
During our August 2025 surveys, we noted that the water level of 70413, as well as the flow of the northern inlet of 70413, were significantly less than they had been during our surveys in July 2024.
Although speculative, we wonder if the retreating water level of 70413 in August 2025 was pushing salamanders from nearby habitats to the lake shore in search of moisture.
<!--# PL and I discussed adding a sentence or two to address the comparative lack of water in the Lyell Basin in 2025. Maybe adding this sort of speculation to this note is not appropriate? but we both supposed that the shoreline where we saw 60+ individuals in 2025 had been underwater in 2024. Feel free to edit. -GL -->

Our observations of *H. platycephalus* indicate that, in addition to their known association with upland habitats in the Sierra Nevada, the species also utilizes lake shore habitats and even underwater littoral habitats of lakes.
The unusually high abundance of *H. platycephalus* observed along lake shores during some surveys suggests the importance of these lentic habitats for this poorly-understood species.

Possible photos/videos for inclusion: South Lyell: IMG_2468 2.MOV, IMG_2478 2.MOV, IMG_2470.HEIC

FIG.
1.
Short but descriptive caption that includes the scientific name of the pictured organism.
PHOTO BY \[name of photographer, if applicable\]

AUTHOR 1 NAME, AUTHOR 2 NAME, AUTHOR 3 NAME, AUTHOR 4 NAME, AUTHOR 5 NAME and ROLAND A. KNAPP, Sierra Nevada Aquatic Research Laboratory, University of California, Mammoth Lakes, California 93546, USA & Earth Research Institute, University of California, Santa Barbara, California 93106, USA <!--# We could include everyone's email, or just one or two of the authors. Given the number of authors, including emails for every author might be a bit much. Maybe include for first and last authors?-->

<!--# Authors (in alphabetical order by last name): Allie Chipman (?), Roland Knapp, Parker Land, Georgia Lattig, Forest Peri, Cob Staines, Leonie Walderich. Anybody else? Decide on order, with Roland last.  -->
